001:
  username: root
  password: Hiamscs123
  enablepass: Hiamscs123
002:
  username: gAAAAABfBEBVSco3tOgLlz1x40vHAbC3Uf4EXQlFz-V16cIejjG31FKpkQXnXF-KW61CRqHvFnug7_ANNk8AniTml66tU_Fuvw==
  password: gAAAAABfBEBV-Mbvxyht-g10qqHcOpN-fU2p8zHjZLVNCOnGE_GW0VUZRgpOX9da5MuUB5f8QnXNnkam-5t_Ymna8jaP3iXZbg==
  enablepass: gAAAAABfBEBV5E85dDrYaksNxUq3lhb8HDWKzATYuwTbTC1e0IB2aYsdaMzAJppehLqCd5gGujOywytiIAnHwHVeQ5TgZdtQBA==